//
//  CommentaryData.m
//  RacePad
//
//  Created by Gareth Griffith on 1/19/11.
//  Copyright 2011 SBG Racing Services Ltd. All rights reserved.
//

#import "RacePadDatabase.h"
#import "CommentaryData.h"

@implementation CommentaryData

- (void) fillWithDefaultData:(int)car
{
	if(car == RPD_BLUE_CAR_)
	{
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:1 TimeStamp:48600.3 Focus:@"" Description:@"GREEN LIGHT"];
		[self addItemWithType:ALERT_RACE_EVENT_ Lap:1 TimeStamp:50610.6 Focus:@"" Description:@"RACE START"];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:1 TimeStamp:50681.1 Focus:@"MSC" Description:@"Michael overtook J.Trulli at turn 10 for 16th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50729.1 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 1 lap"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50729.1 Focus:@"HAM" Description:@"Michael is 9.5s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:1 TimeStamp:50738.4 Focus:@"MSC" Description:@"Michael completed lap 1 in 14th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:1 TimeStamp:50738.4 Focus:@"MSC" Description:@"S.Yamamoto is 1.1s ahead. V.Petrov is 1.4s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50734.1 Focus:@"BUT" Description:@"J.Button overtook F.Massa at turn 1 for 4th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50738.5 Focus:@"BUT" Description:@"J.Button overtook S.Vettel at turn 1 for 3rd place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50758.7 Focus:@"BUT" Description:@"J.Button overtook R.Kubica at turn 4 for 2nd place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50769.6 Focus:@"MSC" Description:@"Michael was overtaken by V.Petrov at turn 4, dropping to 14th place."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:1 TimeStamp:50782.3 Focus:@"BAR" Description:@"Rubens Barrichello is out of the race."];
		[self addItemWithType:ALERT_SAFETY_CAR_ Lap:2 TimeStamp:50823.5 Focus:@"" Description:@"SAFETY CAR DEPLOYED"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50880.3 Focus:@"MSC" Description:@"Michael completed lap 2 in 13th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50880.3 Focus:@"MSC" Description:@"K.Kobayashi is 0.6s ahead. J.Alguersuari is 0.8s behind."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:2 TimeStamp:50890.3 Focus:@"MSC" Description:@"We are not stopping the cars as we think the rain will not last long."];
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:3 TimeStamp:51040.6 Focus:@"" Description:@"TRACK CLEAR"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:3 TimeStamp:51058.2 Focus:@"MSC" Description:@"Michael completed lap 3 in 12th place. The safety car is in."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:3 TimeStamp:51058.2 Focus:@"MSC" Description:@"V.Petrov is 0.4s ahead. J.Trulli is 1.4s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:4 TimeStamp:51063.7 Focus:@"VET" Description:@"S.Vettel overtook R.Kubica at turn 1 for 3rd place."];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51095.3 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 36.807"];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51148.3 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 53.101"];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:51149.1 Focus:@"MSC" Description:@"Michael is on Prime tyres."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51171.1 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 4 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51171.1 Focus:@"HAM" Description:@"Michael is 8.8s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51179.8 Focus:@"MSC" Description:@"Michael completed lap 4 in 12th place with a 2:01.575."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51179.8 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51179.8 Focus:@"MSC" Description:@"V.Petrov is 0.6s ahead. J.Trulli is 4.2s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51180.0 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 31.667"];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51213.8 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 33.844"];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51265.0 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 51.187"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51295.2 Focus:@"MSC" Description:@"Michael completed lap 5 in 12th place with a 1:55.431."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51295.2 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51295.2 Focus:@"MSC" Description:@"V.Petrov is 0.7s ahead. J.Trulli is 7.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51295.5 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 30.400"];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51328.4 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.977"];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51379.6 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 51.079"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51409.6 Focus:@"MSC" Description:@"Michael completed lap 6 in 12th place with a 1:54.417."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51409.6 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51409.6 Focus:@"MSC" Description:@"V.Petrov is 0.3s ahead. K.Kobayashi is 7.5s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51409.8 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 30.361"];
		[self addItemWithType:ALERT_INFO_ Lap:7 TimeStamp:51442.8 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.885"];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:5 TimeStamp:51482.4 Focus:@"SEN" Description:@"Bruno Senna is out of the race."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:7 TimeStamp:51524.1 Focus:@"MSC" Description:@"Michael completed lap 7 in 12th place with a 1:54.475."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:7 TimeStamp:51524.1 Focus:@"MSC" Description:@"V.Petrov is 0.1s ahead. K.Kobayashi is 6.0s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:7 TimeStamp:51524.4 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 30.147"];
		[self addItemWithType:ALERT_INFO_ Lap:8 TimeStamp:51557.0 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.756"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51620.2 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 8 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51620.2 Focus:@"HAM" Description:@"Michael is 18.9s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:8 TimeStamp:51639.2 Focus:@"MSC" Description:@"Michael completed lap 8 in 12th place with a 1:55.122."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:8 TimeStamp:51639.2 Focus:@"MSC" Description:@"V.Petrov is 0.9s ahead. K.Kobayashi is 4.2s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51753.7 Focus:@"MSC" Description:@"Michael completed lap 9 in 12th place with a 1:54.496."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51753.7 Focus:@"MSC" Description:@"V.Petrov is 0.6s ahead. K.Kobayashi is 3.2s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:10 TimeStamp:51786.6 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.706"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:10 TimeStamp:51868.9 Focus:@"MSC" Description:@"Michael completed lap 10 in 11th place with a 1:55.149."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:10 TimeStamp:51868.9 Focus:@"MSC" Description:@"V.Petrov is 0.5s ahead. V.Liuzzi is 1.1s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:11 TimeStamp:51910.5 Focus:@"MSC" Description:@"Michael overtook N.Rosberg at turn 7 for 10th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:11 TimeStamp:51983.9 Focus:@"MSC" Description:@"Michael completed lap 11 in 10th place with a 1:55.093."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:11 TimeStamp:51983.9 Focus:@"MSC" Description:@"V.Petrov is 1.0s ahead. N.Rosberg is 0.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:12 TimeStamp:52067.8 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 50.579"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52072.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 12 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52072.0 Focus:@"HAM" Description:@"Michael is 25.8s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:12 TimeStamp:52097.6 Focus:@"MSC" Description:@"Michael completed lap 12 in 10th place with a 1:53.663."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:12 TimeStamp:52097.6 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:12 TimeStamp:52097.6 Focus:@"MSC" Description:@"V.Petrov is 0.8s ahead. N.Rosberg is 1.7s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:12 TimeStamp:52097.9 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 30.074"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52211.7 Focus:@"MSC" Description:@"Michael completed lap 13 in 10th place with a 1:54.064."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52211.7 Focus:@"MSC" Description:@"V.Petrov is 1.4s ahead. N.Rosberg is 2.0s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:14 TimeStamp:52325.4 Focus:@"MSC" Description:@"Michael completed lap 14 in 10th place with a 1:53.771."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:14 TimeStamp:52325.4 Focus:@"MSC" Description:@"V.Petrov is 1.9s ahead. N.Rosberg is 2.5s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:15 TimeStamp:52439.9 Focus:@"MSC" Description:@"Michael completed lap 15 in 10th place with a 1:54.462."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:15 TimeStamp:52439.9 Focus:@"MSC" Description:@"V.Petrov is 2.9s ahead. N.Rosberg is 2.2s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52523.5 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 16 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52523.5 Focus:@"HAM" Description:@"Michael is 30.6s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:16 TimeStamp:52554.6 Focus:@"MSC" Description:@"Michael completed lap 16 in 8th place with a 1:54.682."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:16 TimeStamp:52554.6 Focus:@"MSC" Description:@"N.Hulkenberg is 1.8s ahead. V.Petrov is 1.3s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:16 TimeStamp:52592.2 Focus:@"BUT" Description:@"Jenson Button is out of the race."];
		[self addItemWithType:ALERT_INFO_ Lap:17 TimeStamp:52638.8 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 50.370"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52668.8 Focus:@"MSC" Description:@"Michael completed lap 17 in 6th place with a 1:54.176."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52668.8 Focus:@"MSC" Description:@"A.Sutil is 14.5s ahead. N.Rosberg is 2.3s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:18 TimeStamp:52752.2 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 50.335"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52782.3 Focus:@"MSC" Description:@"Michael completed lap 18 in 6th place with a 1:53.521."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52782.3 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52782.3 Focus:@"MSC" Description:@"A.Sutil is 14.7s ahead. N.Rosberg is 2.5s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:19 TimeStamp:52897.6 Focus:@"MSC" Description:@"Michael completed lap 19 in 6th place with a 1:55.362."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:19 TimeStamp:52897.6 Focus:@"MSC" Description:@"A.Sutil is 13.9s ahead. N.Rosberg is 2.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:52978.6 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 20 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:52978.6 Focus:@"HAM" Description:@"Michael is 32.9s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:20 TimeStamp:53011.6 Focus:@"MSC" Description:@"Michael completed lap 20 in 6th place with a 1:53.954."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:20 TimeStamp:53011.6 Focus:@"MSC" Description:@"A.Sutil is 12.9s ahead. N.Rosberg is 2.3s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:21 TimeStamp:53095.8 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 50.326"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:53125.5 Focus:@"MSC" Description:@"Michael completed lap 21 in 6th place with a 1:53.899."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:53125.5 Focus:@"MSC" Description:@"A.Sutil is 10.2s ahead. N.Rosberg is 1.4s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:22 TimeStamp:53208.4 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 49.968"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:22 TimeStamp:53215.9 Focus:@"WEB" Description:@"Mark Webber pitted from 3rd place on lap 22"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:22 TimeStamp:53238.4 Focus:@"MSC" Description:@"Michael completed lap 22 in 5th place with a 1:52.927."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:22 TimeStamp:53238.4 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:22 TimeStamp:53238.4 Focus:@"MSC" Description:@"M.Webber is 19.8s ahead. N.Rosberg is 1.9s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:23 TimeStamp:53241.6 Focus:@"WEB" Description:@"M.Webber came out of the pits in 4th place"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:23 TimeStamp:53325.5 Focus:@"KUB" Description:@"Robert Kubica pitted from 2nd place on lap 23"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:23 TimeStamp:53331.0 Focus:@"MAS" Description:@"Felipe Massa pitted from 3rd place on lap 23"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53351.4 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:23 TimeStamp:53351.7 Focus:@"MSC" Description:@"Michael completed lap 23 in 5th place with a 1:53.247."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:23 TimeStamp:53351.7 Focus:@"MSC" Description:@"F.Massa is 17.9s ahead. N.Rosberg is 1.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:23 TimeStamp:53352.4 Focus:@"WEB" Description:@"M.Webber came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53357.2 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53384.6 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.680"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:24 TimeStamp:53426.1 Focus:@"HAM" Description:@"Lewis Hamilton pitted from the lead on lap 24"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53434.6 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 49.821"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53452.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 24 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53452.0 Focus:@"HAM" Description:@"Michael is 12.3s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53452.6 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53462.5 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53464.2 Focus:@"MSC" Description:@"Michael completed lap 24 in 5th place with a 1:52.489."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53464.2 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53464.2 Focus:@"MSC" Description:@"F.Massa is 6.2s ahead. A.Sutil is 0.5s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53464.4 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 29.988"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53468.9 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:25 TimeStamp:53493.5 Focus:@"MSC" Description:@"Michael was overtaken by A.Sutil at turn 5, dropping to 6th place."];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53497.1 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.610"];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53563.4 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53577.4 Focus:@"MSC" Description:@"Michael completed lap 25 in 6th place with a 1:53.194."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53577.4 Focus:@"MSC" Description:@"A.Sutil is 2.2s ahead. N.Rosberg is 1.2s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53577.6 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 29.896"];
		[self addItemWithType:ALERT_INFO_ Lap:26 TimeStamp:53610.1 Focus:@"MSC" Description:@"Michael just set his best sector 1 of the race so far : 32.417"];
		[self addItemWithType:ALERT_INFO_ Lap:26 TimeStamp:53659.8 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 49.738"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:26 TimeStamp:53689.5 Focus:@"MSC" Description:@"Michael completed lap 26 in 6th place with a 1:52.117."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:26 TimeStamp:53689.5 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:26 TimeStamp:53689.5 Focus:@"MSC" Description:@"A.Sutil is 3.6s ahead. N.Rosberg is 1.4s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:27 TimeStamp:53771.9 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 49.548"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:27 TimeStamp:53801.6 Focus:@"MSC" Description:@"Michael completed lap 27 in 6th place with a 1:52.152."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:27 TimeStamp:53801.6 Focus:@"MSC" Description:@"A.Sutil is 4.1s ahead. N.Rosberg is 2.0s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:28 TimeStamp:53884.1 Focus:@"MSC" Description:@"Michael just set his best sector 2 of the race so far : 49.452"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:53884.7 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 28 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:53884.7 Focus:@"HAM" Description:@"Michael is 28.8s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:28 TimeStamp:53913.7 Focus:@"MSC" Description:@"Michael completed lap 28 in 6th place with a 1:52.098."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:28 TimeStamp:53913.7 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:28 TimeStamp:53913.7 Focus:@"MSC" Description:@"A.Sutil is 4.5s ahead. N.Rosberg is 2.6s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:54026.1 Focus:@"MSC" Description:@"Michael completed lap 29 in 6th place with a 1:52.387."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:54026.1 Focus:@"MSC" Description:@"A.Sutil is 5.8s ahead. N.Rosberg is 2.3s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:30 TimeStamp:54138.4 Focus:@"MSC" Description:@"Michael completed lap 30 in 6th place with a 1:52.305."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:30 TimeStamp:54138.4 Focus:@"MSC" Description:@"A.Sutil is 6.8s ahead. N.Rosberg is 2.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:31 TimeStamp:54250.6 Focus:@"MSC" Description:@"Michael completed lap 31 in 6th place with a 1:52.185."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:31 TimeStamp:54250.6 Focus:@"MSC" Description:@"A.Sutil is 7.5s ahead. N.Rosberg is 1.8s behind."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:31 TimeStamp:54272.3 Focus:@"MSC" Description:@"Weather will decide this race for us now."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:31 TimeStamp:54272.3 Focus:@"MSC" Description:@"We need it to rain in the next 4 or 5 laps."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54322.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 32 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54322.0 Focus:@"HAM" Description:@"Michael is 39.8s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:32 TimeStamp:54362.5 Focus:@"MSC" Description:@"Michael completed lap 32 in 6th place with a 1:51.914."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:32 TimeStamp:54362.5 Focus:@"MSC" Description:@"That is Michael's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:32 TimeStamp:54362.5 Focus:@"MSC" Description:@"A.Sutil is 8.4s ahead. N.Rosberg is 1.9s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:32 TimeStamp:54362.8 Focus:@"MSC" Description:@"Michael just set his best sector 3 of the race so far : 29.892"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54477.1 Focus:@"MSC" Description:@"Michael completed lap 33 in 6th place with a 1:54.566."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54477.1 Focus:@"MSC" Description:@"A.Sutil is 11.1s ahead. N.Rosberg is 2.6s behind."];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:34 TimeStamp:54601.1 Focus:@"MSC" Description:@"Michael pitted on lap 34"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:34 TimeStamp:54605.7 Focus:@"ROS" Description:@"Nico pitted on lap 34"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54696.6 Focus:@"HAM" Description:@"Lewis Hamilton pitted from the lead on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54700.7 Focus:@"KUB" Description:@"Robert Kubica pitted from 2nd place on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54702.1 Focus:@"WEB" Description:@"Mark Webber pitted from 3rd place on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54713.0 Focus:@"MAS" Description:@"Felipe Massa pitted from 4th place on lap 35"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54725.3 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54733.3 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54741.5 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:35 TimeStamp:54742.1 Focus:@"MSC" Description:@"Michael completed lap 35 in 6th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:35 TimeStamp:54742.1 Focus:@"MSC" Description:@"A.Sutil is 5.9s ahead. K.Kobayashi is 1.5s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:35 TimeStamp:54753.3 Focus:@"MSC" Description:@"Michael came out of the pits in 6th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54837.6 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 36 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54837.6 Focus:@"HAM" Description:@"Michael is 26.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:54845.2 Focus:@"MSC" Description:@"Michael is on Inter tyres."];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:54845.2 Focus:@"MSC" Description:@"Under the rules, Michael does not need to stop again for tyres."];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54848.5 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54851.4 Focus:@"WEB" Description:@"M.Webber came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54856.0 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54862.8 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:36 TimeStamp:54863.7 Focus:@"MSC" Description:@"Michael completed lap 36 in 6th place with a 2:01.650."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:36 TimeStamp:54863.7 Focus:@"MSC" Description:@"A.Sutil is 5.1s ahead. K.Kobayashi is 1.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54986.6 Focus:@"MSC" Description:@"Michael completed lap 37 in 6th place with a 2:02.901."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54986.6 Focus:@"MSC" Description:@"A.Sutil is 6.2s ahead. K.Kobayashi is 0.7s behind."];
		[self addItemWithType:ALERT_SAFETY_CAR_ Lap:38 TimeStamp:55067.4 Focus:@"" Description:@"SAFETY CAR DEPLOYED"];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:38 TimeStamp:55112.4 Focus:@"ALO" Description:@"Fernando Alonso is out of the race."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:38 TimeStamp:55116.5 Focus:@"MSC" Description:@"Michael completed lap 38 in 6th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:38 TimeStamp:55116.5 Focus:@"MSC" Description:@"A.Sutil is 5.1s ahead. K.Kobayashi is 0.9s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.2 Focus:@"KUB" Description:@"Robert Kubica is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:38 TimeStamp:55222.4 Focus:@"HUL" Description:@"Nico Hulkenberg is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.4 Focus:@"WEB" Description:@"Mark Webber is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.4 Focus:@"HAM" Description:@"Lewis Hamilton is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55232.4 Focus:@"SUT" Description:@"Adrian Sutil is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55232.4 Focus:@"MAS" Description:@"Felipe Massa is out of the race."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:39 TimeStamp:55283.8 Focus:@"MSC" Description:@"Michael completed lap 39 in 6th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:39 TimeStamp:55283.8 Focus:@"MSC" Description:@"A.Sutil is 0.9s ahead. K.Kobayashi is 0.4s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:40 TimeStamp:55422.2 Focus:@"SUT" Description:@"Adrian Sutil is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:40 TimeStamp:55422.4 Focus:@"MAS" Description:@"Felipe Massa is out of the race."];
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:40 TimeStamp:55459.5 Focus:@"" Description:@"TRACK CLEAR"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55467.8 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 40 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55467.8 Focus:@"HAM" Description:@"Michael is 4.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:40 TimeStamp:55471.7 Focus:@"MSC" Description:@"Michael completed lap 40 in 6th place. The safety car is in."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:40 TimeStamp:55471.7 Focus:@"MSC" Description:@"A.Sutil is 0.4s ahead. K.Kobayashi is 0.5s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:41 TimeStamp:55502.4 Focus:@"MSC" Description:@"Michael was overtaken by N.Rosberg at turn 4, dropping to 7th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55599.7 Focus:@"MSC" Description:@"Michael completed lap 41 in 7th place with a 2:08.008."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55599.7 Focus:@"MSC" Description:@"N.Rosberg is 1.1s ahead. K.Kobayashi is 2.3s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:42 TimeStamp:55723.9 Focus:@"MSC" Description:@"Michael completed lap 42 in 7th place with a 2:04.252."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:42 TimeStamp:55723.9 Focus:@"MSC" Description:@"N.Rosberg is 2.1s ahead. K.Kobayashi is 2.8s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:43 TimeStamp:55846.7 Focus:@"MSC" Description:@"Michael completed lap 43 in 7th place with a 2:02.735."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:43 TimeStamp:55846.7 Focus:@"MSC" Description:@"N.Rosberg is 3.2s ahead. K.Kobayashi is 2.7s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:45 TimeStamp:55954.6 Focus:@"HAM" Description:@"L.Hamilton has won the race"];
		[self addItemWithType:ALERT_CHEQUERED_FLAG_ Lap:44 TimeStamp:55954.6 Focus:@"" Description:@"CHEQUERED FLAG"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:44 TimeStamp:55969.7 Focus:@"MSC" Description:@"Michael finished the race in 7th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:44 TimeStamp:55969.7 Focus:@"MSC" Description:@"N.Rosberg is 3.3s ahead. K.Kobayashi is 1.0s behind."];
	}
	else
	{
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:1 TimeStamp:48600.3 Focus:@"" Description:@"GREEN LIGHT"];
		[self addItemWithType:ALERT_RACE_EVENT_ Lap:1 TimeStamp:50610.6 Focus:@"" Description:@"RACE START"];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:1 TimeStamp:50649.4 Focus:@"ROS" Description:@"Nico overtook J.Alguersuari at turn 5 for 11th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:1 TimeStamp:50649.4 Focus:@"ROS" Description:@"Nico overtook V.Liuzzi at turn 5 for 11th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:1 TimeStamp:50653.3 Focus:@"ROS" Description:@"Nico overtook N.Hulkenberg at turn 6 for 10th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50729.1 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 1 lap"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50729.1 Focus:@"HAM" Description:@"Nico is 5.7s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50731.2 Focus:@"ROS" Description:@"Nico was overtaken by N.Hulkenberg at turn 19, dropping to 8th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:1 TimeStamp:50733.6 Focus:@"ROS" Description:@"Nico completed lap 1 in 9th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:1 TimeStamp:50733.6 Focus:@"ROS" Description:@"A.Sutil is 0.1s ahead. R.Barrichello is 2.2s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50734.1 Focus:@"BUT" Description:@"J.Button overtook F.Massa at turn 1 for 4th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50738.5 Focus:@"BUT" Description:@"J.Button overtook S.Vettel at turn 1 for 3rd place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50741.7 Focus:@"ROS" Description:@"Nico was overtaken by J.Alguersuari at turn 1, dropping to 10th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50758.7 Focus:@"BUT" Description:@"J.Button overtook R.Kubica at turn 4 for 2nd place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50764.0 Focus:@"ROS" Description:@"Nico overtook J.Alguersuari at turn 4 for 9th place."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:1 TimeStamp:50782.3 Focus:@"BAR" Description:@"Rubens Barrichello is out of the race."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:2 TimeStamp:50774.1 Focus:@"ROS" Description:@"Nico was overtaken by V.Liuzzi at turn 5, dropping to 10th place."];
		[self addItemWithType:ALERT_SAFETY_CAR_ Lap:2 TimeStamp:50823.5 Focus:@"" Description:@"SAFETY CAR DEPLOYED"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50876.6 Focus:@"ROS" Description:@"Nico completed lap 2 in 10th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:2 TimeStamp:50876.6 Focus:@"ROS" Description:@"V.Liuzzi is 1.3s ahead. K.Kobayashi is 2.1s behind."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:2 TimeStamp:50890.3 Focus:@"ROS" Description:@"We are not stopping the cars as we think the rain will not last long."];
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:3 TimeStamp:51040.6 Focus:@"" Description:@"TRACK CLEAR"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:3 TimeStamp:51057.1 Focus:@"ROS" Description:@"Nico completed lap 3 in 10th place. The safety car is in."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:3 TimeStamp:51057.1 Focus:@"ROS" Description:@"V.Liuzzi is 0.3s ahead. V.Petrov is 0.7s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:4 TimeStamp:51063.7 Focus:@"VET" Description:@"S.Vettel overtook R.Kubica at turn 1 for 3rd place."];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51092.8 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 35.680"];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:51145.2 Focus:@"ROS" Description:@"Nico is on Prime tyres."];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51146.8 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 53.916"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51171.1 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 4 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51171.1 Focus:@"HAM" Description:@"Nico is 6.9s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51177.9 Focus:@"ROS" Description:@"Nico completed lap 4 in 10th place with a 2:00.843."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51177.9 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:4 TimeStamp:51177.9 Focus:@"ROS" Description:@"V.Liuzzi is 0.3s ahead. V.Petrov is 1.4s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:4 TimeStamp:51178.0 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 31.247"];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51211.5 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 33.465"];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51263.5 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 51.911"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51293.8 Focus:@"ROS" Description:@"Nico completed lap 5 in 10th place with a 1:55.874."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51293.8 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:5 TimeStamp:51293.8 Focus:@"ROS" Description:@"V.Liuzzi is 0.6s ahead. V.Petrov is 0.9s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:5 TimeStamp:51294.0 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 30.498"];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51326.8 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.918"];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51378.6 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 51.544"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51408.4 Focus:@"ROS" Description:@"Nico completed lap 6 in 10th place with a 1:54.697."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51408.4 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:6 TimeStamp:51408.4 Focus:@"ROS" Description:@"V.Liuzzi is 0.5s ahead. V.Petrov is 0.9s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:6 TimeStamp:51408.6 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 30.235"];
		[self addItemWithType:ALERT_INFO_ Lap:7 TimeStamp:51441.5 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.782"];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:5 TimeStamp:51482.4 Focus:@"SEN" Description:@"Bruno Senna is out of the race."];
		[self addItemWithType:ALERT_INFO_ Lap:7 TimeStamp:51492.7 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 51.369"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:7 TimeStamp:51522.9 Focus:@"ROS" Description:@"Nico completed lap 7 in 10th place with a 1:54.432."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:7 TimeStamp:51522.9 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:7 TimeStamp:51522.9 Focus:@"ROS" Description:@"V.Liuzzi is 0.4s ahead. V.Petrov is 0.9s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51620.2 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 8 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51620.2 Focus:@"HAM" Description:@"Nico is 17.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:8 TimeStamp:51637.8 Focus:@"ROS" Description:@"Nico completed lap 8 in 10th place with a 1:54.895."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:8 TimeStamp:51637.8 Focus:@"ROS" Description:@"V.Liuzzi is 0.5s ahead. V.Petrov is 0.7s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51752.6 Focus:@"ROS" Description:@"Nico completed lap 9 in 10th place with a 1:54.884."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:9 TimeStamp:51752.6 Focus:@"ROS" Description:@"V.Liuzzi is 0.3s ahead. V.Petrov is 0.4s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:10 TimeStamp:51785.3 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.518"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:10 TimeStamp:51868.0 Focus:@"ROS" Description:@"Nico completed lap 10 in 9th place with a 1:55.360."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:10 TimeStamp:51868.0 Focus:@"ROS" Description:@"N.Hulkenberg is 5.0s ahead. V.Petrov is 0.4s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:11 TimeStamp:51906.1 Focus:@"ROS" Description:@"Nico was overtaken by V.Petrov at turn 6, dropping to 10th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:11 TimeStamp:51910.5 Focus:@"ROS" Description:@"Nico was overtaken by M.Schumacher at turn 7, dropping to 11th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:11 TimeStamp:51984.8 Focus:@"ROS" Description:@"Nico completed lap 11 in 11th place with a 1:56.798."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:11 TimeStamp:51984.8 Focus:@"ROS" Description:@"M.Schumacher is 0.8s ahead. K.Kobayashi is 0.7s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:11 TimeStamp:51985.1 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 30.115"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52072.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 12 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52072.0 Focus:@"HAM" Description:@"Nico is 27.3s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:12 TimeStamp:52099.4 Focus:@"ROS" Description:@"Nico completed lap 12 in 11th place with a 1:54.620."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:12 TimeStamp:52099.4 Focus:@"ROS" Description:@"M.Schumacher is 1.8s ahead. K.Kobayashi is 0.5s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:13 TimeStamp:52183.9 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 51.314"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52213.6 Focus:@"ROS" Description:@"Nico completed lap 13 in 11th place with a 1:54.202."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52213.6 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:13 TimeStamp:52213.6 Focus:@"ROS" Description:@"M.Schumacher is 1.9s ahead. K.Kobayashi is 0.6s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:13 TimeStamp:52213.9 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 30.101"];
		[self addItemWithType:ALERT_INFO_ Lap:14 TimeStamp:52298.9 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 51.184"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:14 TimeStamp:52328.0 Focus:@"ROS" Description:@"Nico completed lap 14 in 11th place with a 1:54.347."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:14 TimeStamp:52328.0 Focus:@"ROS" Description:@"M.Schumacher is 2.5s ahead. K.Kobayashi is 1.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:15 TimeStamp:52442.2 Focus:@"ROS" Description:@"Nico completed lap 15 in 11th place with a 1:54.225."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:15 TimeStamp:52442.2 Focus:@"ROS" Description:@"M.Schumacher is 2.2s ahead. K.Kobayashi is 2.0s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52523.5 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 16 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52523.5 Focus:@"HAM" Description:@"Nico is 33.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:16 TimeStamp:52557.2 Focus:@"ROS" Description:@"Nico completed lap 16 in 10th place with a 1:54.964."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:16 TimeStamp:52557.2 Focus:@"ROS" Description:@"K.Kobayashi is 1.9s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:16 TimeStamp:52592.2 Focus:@"BUT" Description:@"Jenson Button is out of the race."];
		[self addItemWithType:ALERT_INFO_ Lap:17 TimeStamp:52640.8 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 50.728"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52671.1 Focus:@"ROS" Description:@"Nico completed lap 17 in 7th place with a 1:53.975."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52671.1 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:17 TimeStamp:52671.1 Focus:@"ROS" Description:@"M.Schumacher is 2.3s ahead. K.Kobayashi is 1.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:18 TimeStamp:52754.8 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 50.662"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52784.8 Focus:@"ROS" Description:@"Nico completed lap 18 in 7th place with a 1:53.637."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52784.8 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:18 TimeStamp:52784.8 Focus:@"ROS" Description:@"M.Schumacher is 2.5s ahead. K.Kobayashi is 1.7s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:19 TimeStamp:52899.6 Focus:@"ROS" Description:@"Nico completed lap 19 in 7th place with a 1:54.822."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:19 TimeStamp:52899.6 Focus:@"ROS" Description:@"M.Schumacher is 2.1s ahead. K.Kobayashi is 1.7s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:20 TimeStamp:52932.4 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.517"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:52978.6 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 20 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:52978.6 Focus:@"HAM" Description:@"Nico is 35.2s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:20 TimeStamp:53013.9 Focus:@"ROS" Description:@"Nico completed lap 20 in 7th place with a 1:54.352."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:20 TimeStamp:53013.9 Focus:@"ROS" Description:@"M.Schumacher is 2.2s ahead. K.Kobayashi is 1.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:21 TimeStamp:53046.6 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.512"];
		[self addItemWithType:ALERT_INFO_ Lap:21 TimeStamp:53097.2 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 50.576"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:53127.0 Focus:@"ROS" Description:@"Nico completed lap 21 in 7th place with a 1:53.085."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:53127.0 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:21 TimeStamp:53127.0 Focus:@"ROS" Description:@"M.Schumacher is 1.4s ahead. K.Kobayashi is 1.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:21 TimeStamp:53127.3 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 29.997"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:22 TimeStamp:53215.9 Focus:@"WEB" Description:@"Mark Webber pitted from 3rd place on lap 22"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:22 TimeStamp:53240.4 Focus:@"ROS" Description:@"Nico completed lap 22 in 6th place with a 1:53.341."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:22 TimeStamp:53240.4 Focus:@"ROS" Description:@"M.Schumacher is 1.9s ahead. K.Kobayashi is 1.0s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:22 TimeStamp:53240.6 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 29.979"];
		[self addItemWithType:ALERT_INFO_ Lap:23 TimeStamp:53241.6 Focus:@"WEB" Description:@"M.Webber came out of the pits in 4th place"];
		[self addItemWithType:ALERT_INFO_ Lap:23 TimeStamp:53323.5 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 50.315"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:23 TimeStamp:53325.5 Focus:@"KUB" Description:@"Robert Kubica pitted from 2nd place on lap 23"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:23 TimeStamp:53331.0 Focus:@"MAS" Description:@"Felipe Massa pitted from 3rd place on lap 23"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53351.4 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_INFO_ Lap:23 TimeStamp:53352.4 Focus:@"WEB" Description:@"M.Webber came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:23 TimeStamp:53353.6 Focus:@"ROS" Description:@"Nico completed lap 23 in 6th place with a 1:53.200."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:23 TimeStamp:53353.6 Focus:@"ROS" Description:@"M.Schumacher is 1.8s ahead. A.Sutil is 0.3s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53357.2 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:24 TimeStamp:53382.1 Focus:@"ROS" Description:@"Nico was overtaken by A.Sutil at turn 5, dropping to 7th place."];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53386.3 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.455"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:24 TimeStamp:53426.1 Focus:@"HAM" Description:@"Lewis Hamilton pitted from the lead on lap 24"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53452.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 24 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53452.0 Focus:@"HAM" Description:@"Nico is 40.9s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53452.6 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53462.5 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53466.5 Focus:@"ROS" Description:@"Nico completed lap 24 in 7th place with a 1:52.946."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53466.5 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:24 TimeStamp:53466.5 Focus:@"ROS" Description:@"A.Sutil is 1.8s ahead. K.Kobayashi is 1.6s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53466.8 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 29.874"];
		[self addItemWithType:ALERT_INFO_ Lap:24 TimeStamp:53468.9 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53499.3 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.429"];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53549.3 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 50.043"];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53563.4 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53578.7 Focus:@"ROS" Description:@"Nico completed lap 25 in 7th place with a 1:52.175."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53578.7 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:25 TimeStamp:53578.7 Focus:@"ROS" Description:@"M.Schumacher is 1.3s ahead. K.Kobayashi is 2.5s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:25 TimeStamp:53579.0 Focus:@"ROS" Description:@"Nico just set his best sector 3 of the race so far : 29.703"];
		[self addItemWithType:ALERT_INFO_ Lap:26 TimeStamp:53611.1 Focus:@"ROS" Description:@"Nico just set his best sector 1 of the race so far : 32.133"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:26 TimeStamp:53691.0 Focus:@"ROS" Description:@"Nico completed lap 26 in 7th place with a 1:52.275."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:26 TimeStamp:53691.0 Focus:@"ROS" Description:@"M.Schumacher is 1.4s ahead. K.Kobayashi is 2.6s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:27 TimeStamp:53803.9 Focus:@"ROS" Description:@"Nico completed lap 27 in 7th place with a 1:52.929."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:27 TimeStamp:53803.9 Focus:@"ROS" Description:@"M.Schumacher is 2.0s ahead. K.Kobayashi is 2.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:53884.7 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 28 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:53884.7 Focus:@"HAM" Description:@"Nico is 31.6s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:28 TimeStamp:53916.3 Focus:@"ROS" Description:@"Nico completed lap 28 in 7th place with a 1:52.458."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:28 TimeStamp:53916.3 Focus:@"ROS" Description:@"M.Schumacher is 2.5s ahead. K.Kobayashi is 2.7s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:29 TimeStamp:53998.9 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 49.973"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:54028.4 Focus:@"ROS" Description:@"Nico completed lap 29 in 7th place with a 1:52.102."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:54028.4 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:29 TimeStamp:54028.4 Focus:@"ROS" Description:@"M.Schumacher is 2.2s ahead. K.Kobayashi is 2.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:30 TimeStamp:54140.8 Focus:@"ROS" Description:@"Nico completed lap 30 in 7th place with a 1:52.375."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:30 TimeStamp:54140.8 Focus:@"ROS" Description:@"M.Schumacher is 2.3s ahead. K.Kobayashi is 3.1s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:31 TimeStamp:54222.9 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 49.704"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:31 TimeStamp:54252.5 Focus:@"ROS" Description:@"Nico completed lap 31 in 7th place with a 1:51.688."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:31 TimeStamp:54252.5 Focus:@"ROS" Description:@"That is Nico's best lap of the race so far."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:31 TimeStamp:54252.5 Focus:@"ROS" Description:@"M.Schumacher is 1.8s ahead. K.Kobayashi is 3.4s behind."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:31 TimeStamp:54272.3 Focus:@"ROS" Description:@"Weather will decide this race for us now."];
		[self addItemWithType:ALERT_PIT_INSIGHT_ Lap:31 TimeStamp:54272.3 Focus:@"ROS" Description:@"We need it to rain in the next 4 or 5 laps."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54322.0 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 32 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54322.0 Focus:@"HAM" Description:@"Nico is 41.7s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:32 TimeStamp:54335.0 Focus:@"ROS" Description:@"Nico just set his best sector 2 of the race so far : 49.682"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:32 TimeStamp:54364.5 Focus:@"ROS" Description:@"Nico completed lap 32 in 7th place with a 1:51.986."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:32 TimeStamp:54364.5 Focus:@"ROS" Description:@"M.Schumacher is 1.9s ahead. K.Kobayashi is 3.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54479.8 Focus:@"ROS" Description:@"Nico completed lap 33 in 7th place with a 1:55.285."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:33 TimeStamp:54479.8 Focus:@"ROS" Description:@"M.Schumacher is 2.6s ahead. K.Kobayashi is 1.2s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:34 TimeStamp:54508.3 Focus:@"ROS" Description:@"Nico was overtaken by K.Kobayashi at turn 4, dropping to 8th place."];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:34 TimeStamp:54601.1 Focus:@"MSC" Description:@"Michael pitted on lap 34"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:34 TimeStamp:54605.7 Focus:@"ROS" Description:@"Nico pitted on lap 34"];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:35 TimeStamp:54592.4 Focus:@"ROS" Description:@"Nico was overtaken by F.Alonso at turn 18, dropping to 9th place."];
		[self addItemWithType:ALERT_INFO_ Lap:35 TimeStamp:54639.1 Focus:@"ROS" Description:@"Nico came out of the pits in 9th place"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54696.6 Focus:@"HAM" Description:@"Lewis Hamilton pitted on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54700.7 Focus:@"KUB" Description:@"Robert Kubica pitted from the lead on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54702.1 Focus:@"WEB" Description:@"Mark Webber pitted from 2nd place on lap 35"];
		[self addItemWithType:ALERT_PIT_STOP_ Lap:35 TimeStamp:54713.0 Focus:@"MAS" Description:@"Felipe Massa pitted from 4th place on lap 35"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54725.3 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54733.3 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54741.5 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:35 TimeStamp:54752.1 Focus:@"ROS" Description:@"Nico completed lap 35 in 9th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:35 TimeStamp:54752.1 Focus:@"ROS" Description:@"F.Alonso is 4.5s ahead. V.Petrov is 3.8s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:35 TimeStamp:54763.3 Focus:@"ROS" Description:@"Nico came out of the pits in 9th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54837.6 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 36 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:54837.6 Focus:@"HAM" Description:@"Nico is 38.6s behind."];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54848.5 Focus:@"HAM" Description:@"L.Hamilton came out of the pits in the lead"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54851.4 Focus:@"WEB" Description:@"M.Webber came out of the pits in 2nd place"];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54856.0 Focus:@"KUB" Description:@"R.Kubica came out of the pits in 3rd place"];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:54858.5 Focus:@"ROS" Description:@"Nico is on Inter tyres."];
		[self addItemWithType:ALERT_INFO_ Lap:0 TimeStamp:54858.5 Focus:@"ROS" Description:@"Under the rules, Nico does not need to stop again for tyres."];
		[self addItemWithType:ALERT_INFO_ Lap:36 TimeStamp:54862.8 Focus:@"MAS" Description:@"F.Massa came out of the pits in 4th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:36 TimeStamp:54877.1 Focus:@"ROS" Description:@"Nico completed lap 36 in 9th place with a 2:04.990."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:36 TimeStamp:54877.1 Focus:@"ROS" Description:@"F.Alonso is 8.6s ahead. V.Petrov is 2.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:55000.8 Focus:@"ROS" Description:@"Nico completed lap 37 in 9th place with a 2:03.666."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:37 TimeStamp:55000.8 Focus:@"ROS" Description:@"F.Alonso is 10.9s ahead. V.Petrov is 1.7s behind."];
		[self addItemWithType:ALERT_SAFETY_CAR_ Lap:38 TimeStamp:55067.4 Focus:@"" Description:@"SAFETY CAR DEPLOYED"];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:38 TimeStamp:55112.4 Focus:@"ALO" Description:@"Fernando Alonso is out of the race."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:38 TimeStamp:55132.8 Focus:@"ROS" Description:@"Nico completed lap 38 in 8th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:38 TimeStamp:55132.8 Focus:@"ROS" Description:@"K.Kobayashi is 15.3s ahead. V.Petrov is 3.1s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.2 Focus:@"KUB" Description:@"Robert Kubica is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:38 TimeStamp:55222.4 Focus:@"HUL" Description:@"Nico Hulkenberg is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.4 Focus:@"WEB" Description:@"Mark Webber is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55222.4 Focus:@"HAM" Description:@"Lewis Hamilton is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55232.4 Focus:@"SUT" Description:@"Adrian Sutil is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:39 TimeStamp:55232.4 Focus:@"MAS" Description:@"Felipe Massa is out of the race."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:39 TimeStamp:55285.9 Focus:@"ROS" Description:@"Nico completed lap 39 in 8th place. The safety car is out."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:39 TimeStamp:55285.9 Focus:@"ROS" Description:@"K.Kobayashi is 1.5s ahead. V.Petrov is 2.1s behind."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:40 TimeStamp:55422.2 Focus:@"SUT" Description:@"Adrian Sutil is out of the race."];
		[self addItemWithType:ALERT_CAR_STOPPED_ Lap:40 TimeStamp:55422.4 Focus:@"MAS" Description:@"Felipe Massa is out of the race."];
		[self addItemWithType:ALERT_GREEN_FLAG_ Lap:40 TimeStamp:55459.5 Focus:@"" Description:@"TRACK CLEAR"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55467.8 Focus:@"HAM" Description:@"L.Hamilton is leading the race after 40 laps"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55467.8 Focus:@"HAM" Description:@"Nico is 5.4s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:40 TimeStamp:55472.5 Focus:@"ROS" Description:@"Nico completed lap 40 in 8th place. The safety car is in."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:40 TimeStamp:55472.5 Focus:@"ROS" Description:@"K.Kobayashi is 0.0s ahead. V.Petrov is 1.1s behind."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:41 TimeStamp:55477.1 Focus:@"ROS" Description:@"Nico overtook K.Kobayashi at turn 1 for 7th place."];
		[self addItemWithType:ALERT_OVERTAKE_ Lap:41 TimeStamp:55502.4 Focus:@"ROS" Description:@"Nico overtook M.Schumacher at turn 4 for 6th place."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55598.8 Focus:@"ROS" Description:@"Nico completed lap 41 in 6th place with a 2:06.280."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:41 TimeStamp:55598.8 Focus:@"ROS" Description:@"A.Sutil is 0.6s ahead. M.Schumacher is 1.1s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:42 TimeStamp:55722.0 Focus:@"ROS" Description:@"Nico completed lap 42 in 6th place with a 2:03.235."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:42 TimeStamp:55722.0 Focus:@"ROS" Description:@"A.Sutil is 1.1s ahead. M.Schumacher is 2.2s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:43 TimeStamp:55843.7 Focus:@"ROS" Description:@"Nico completed lap 43 in 6th place with a 2:01.698."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:43 TimeStamp:55843.7 Focus:@"ROS" Description:@"A.Sutil is 1.4s ahead. M.Schumacher is 3.2s behind."];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:45 TimeStamp:55954.6 Focus:@"HAM" Description:@"L.Hamilton has won the race"];
		[self addItemWithType:ALERT_CHEQUERED_FLAG_ Lap:44 TimeStamp:55954.6 Focus:@"" Description:@"CHEQUERED FLAG"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:44 TimeStamp:55966.6 Focus:@"ROS" Description:@"Nico finished the race in 6th place"];
		[self addItemWithType:ALERT_LAP_COMPLETE_ Lap:44 TimeStamp:55966.6 Focus:@"ROS" Description:@"A.Sutil is 3.2s ahead. M.Schumacher is 3.3s behind."];	}
}

@end
