//
//  RacePadDataHandler.h
//  RacePad
//
//  Created by MarkRiches
//  October 2010
//  Copyright 2010 SBG Racing Services Ltd. All rights reserved.
//

#import "BasePadDataHandler.h"

enum DataVersion {
	RACE_PAD_SPA_2011 = 11,
	RACE_PAD_COMMENTARY_IMPORTANCE = 12,
	RACE_PAD_HEAD_TO_HEAD_BLUE_FLAG = 13,
	RACE_PAD_INTERFACE_VERSION = 13
};

enum ServerCommands {
	RPSC_VERSION_ = BPSC_VERSION_, // 1
	RPSC_EVENT_,				// 2
	RPSC_TRACK_MAP_,			// 3
	RPSC_WHOLE_TIMING_PAGE_ = 5,
	RPSC_UPDATE_TIMING_PAGE_,	// 6
	RPSC_CARS_,					// 7
	RPSC_IMAGE_LIST_ITEM_ = BPSC_IMAGE_LIST_ITEM_,	// 8
	RPSC_FILE_START_ = BPSC_FILE_START_,			// 9
	RPSC_FILE_CHUNK_ = BPSC_FILE_CHUNK_,			// 10
	RPSC_FILE_END_ = BPSC_FILE_END_,				// 11
	RPSC_PROJECT_START_ = BPSC_PROJECT_START_,		// 12
	RPSC_DRIVER_VIEW_,			// 13
	RPSC_ACCEPT_PUSH_DATA_ = BPSC_ACCEPT_PUSH_DATA_,// 14
	RPSC_CANCEL_PROJECT_ = BPSC_CANCEL_PROJECT_,	// 15
	RPSC_COMPLETE_PROJECT_ = BPSC_COMPLETE_PROJECT_,// 16
	RPSC_LAP_COUNT_,			// 17
	RPSC_LAP_COUNTER_,			// 18
	RPSC_PIT_WINDOW_BASE_,		// 19
	RPSC_PIT_WINDOW_,			// 20
	RPSC_TRACK_STATE_,			// 21
	RPSC_PROJECT_RANGE_ = BPSC_PROJECT_RANGE_,		// 22
	RPSC_HTML_FILE_ = BPSC_HTML_FILE_,			// 23
	RPSC_TELEMETRY_,			// 24
	RPSC_DRIVER_NAMES_,			// 25
	RPSC_WHOLE_LEADER_BOARD_,	// 26
	RPSC_UPDATE_LEADER_BOARD_,	// 27
	RPSC_RC_MESSAGES_,			// 28
	RPSC_ALERTS_,				// 29
	RPSC_RETURN_PREDICTION_,	// 30
	RPSC_GAME_STATUS_ = 33,
	RPSC_WHOLE_COMPETITOR_VIEW_,	// 34
	RPSC_UPDATE_COMPETITOR_VIEW_,	// 35
	RPSC_REGISTERED_USER_,		// 36
	RPSC_BAD_USER_,				// 37
	RPSC_LIVE_TIME_ = BPSC_LIVE_TIME_,			// 38
	RPSC_RED_COMMENTARY_,		// 39
	RPSC_BLUE_COMMENTARY_,		// 40
	RPSC_SPONSOR_ = BPSC_SPONSOR_,				// 41
	RPSC_TIME_SYNC_ = BPSC_TIME_SYNC_,			// 42
	RPSC_COMMENTARY_,			// 43
	RPSC_DRIVER_GAP_INFO_,		// 44
	RPSC_NO_ACTION_ = BPSC_NO_ACTION_,			// 45
	RPSC_NOTIFY_NEW_CONNECTION_,				// 46
	RPSC_COMMENTARY_UPDATE_,					// 47
	RPSC_HEAD_TO_HEAD_,			// 48
	RPSC_SESSION_,				// 49
	RPSC_COMMENTARY_NO_CHANGE_, // 50
	RPSC_WHOLE_STANDINGS_VIEW_, // 51
	RPSC_UPDATE_STANDINGS_VIEW_, // 52
	RPSC_DRIVER_VOTING_,		// 53
	RPSC_UPDATE_DRIVER_VIEW_,	// 54
	RPSC_WHOLE_TIMING_PAGE_1_,	// 55
	RPSC_UPDATE_TIMING_PAGE_1_,	// 56
	RPSC_WHOLE_TIMING_PAGE_2_,	// 57
	RPSC_UPDATE_TIMING_PAGE_2_,	// 58
};

@interface RacePadDataHandler : BasePadDataHandler
{
}

- (void) handleCommand:(int) command;

@end
